### ISSUE TITLE
border color 

### ISSUE THREAD

**Issue by turkiasoft** [vizhan-lanars/animated-bottom-navigation-bar-flutter#26]
i want to change border color... 

any solution please...
![image](https://user-images.githubusercontent.com/69857983/137809562-d09907a9-7b30-4b83-9cd6-ea8e2db3c282.png)

**Comment by vizhan-lanars** [comment]
Actually, there is no border. That is an elevation shadow.
But it could be treated as an enhancement )

**Comment by thisiskhan** [comment]
Hey There,
Raza Khan this side, Can I work on this issue!!!.

**Comment by vizhan-lanars** [comment]
Hi, @thisiskhan 
Any help welcome )

**Comment by vizhan-lanars** [comment]
Version 1.0.0

**Comment by turkiasoft** [comment]
thanks you a lot
