### ISSUE TITLE
Customize or disable ontap aniation

### ISSUE THREAD

**Issue by Raider-hub** [vizhan-lanars/animated-bottom-navigation-bar-flutter#37]
Hello devs, thank you for putting this out for us, i would like to disable the ontap animation, but it dosent like there is way. i dont like the zoom animation

**Comment by vizhan-lanars** [comment]
Hi 
That is the core widget feature).
U could fork

**Comment by Raider-hub** [comment]
Alright thank you. i'm still new to flutter. i will try to fork it then modify it. if i have problems i will fall back for your support. thank you alot.
