### ISSUE TITLE
How to make persistent bottom nav bar?

### ISSUE THREAD

**Issue by tologonkudaiberdiuulu** [vizhan-lanars/animated-bottom-navigation-bar-flutter#39]
Hi! I'm using this package as a bottom navigation bar. But in my case, bottom nav bar must be persistent(you can see persistent_bottom_nav_bar, go_router for examples).  How to achieve this? I already tried giving selected tab index for nested routes, but while animating there's blink, like bottom nav bar items being larger for second(or even less) and restoring his actual size or bottom nav bar sliding to another position and returning back. But it's human noticeable for eyes. Can you guide me? How I must use it for persistent bottom bar?
P.S. I have also floating action button as a menu button and some bottom bar items where on tap there will be just dialog(will not navigate to new screen. And if you're in nested route(say, you've clicked for one menu in menu screen), if I click to menu button, it must go back to menu screen.

**Comment by tologonkudaiberdiuulu** [comment]
You can see full example https://github.com/tologonkudaiberdiuulu/sample_persist_bottom_nav_bar

**Comment by DmytroDashkevych** [comment]
Hi! I have looked at your project. Try splitting your CustomScaffold into 2 or more widgets to apply setState to a specific widget.
