### ISSUE TITLE
how to set shadow color and elivation of AnimatedBottomNavigationBar

### ISSUE THREAD

**Issue by jinfagang** [vizhan-lanars/animated-bottom-navigation-bar-flutter#9]
how to set shadow color and elivation of AnimatedBottomNavigationBar?

**Comment by Vizhan** [comment]
There is a parameter:
```
/// Optional custom tab bar elevation.
final double elevation;
```
There is no way to set colored shadow using the widget.
You could try this [gist](https://gist.github.com/coman3/e631fd55cd9cdf9bd4efe8ecfdbb85a7)

**Comment by jinfagang** [comment]
@Vizhan thanks! I found there exists elevation option.

Does it possible to implement support translucent blur effect for the background? If so, that would be very nice. There is another package implemented this and looks every fine:

![image](https://user-images.githubusercontent.com/21303438/104539208-01aa9780-5658-11eb-8a25-4b634026396e.png)

it's custom_navigation_bar.

**Comment by Vizhan** [comment]
Will consider as an enhancement

**Comment by vizhan-lanars** [comment]
Version 1.0.0
